### ISSUE TITLE
Zooming in plot view

### ISSUE THREAD

**Issue by rdornas** [AGAuffret/HistMapR#1]
Hi!

First of all, congratulations and thank you very much indeed for your package. It is really interesting and useful!

I am just having some troubles in order to zoom in at the raster image after the function `click_sample`. I have searched all the internet and I also checked `click` function help from `raster` package, without success.

What do you suggest? Is there a way to zoom in (and out) directly in the plot window to help to choose the best pixels?

Thank you in advance!

**Comment by AGAuffret** [comment]
Hello!
Apologies, I haven't been on Github for a while and kind of assumed I would get an email or something if someone reported an issue.

As far as I know, there isn't a way to zoom the map from within R. For click_sample I have found that using the package has worked best using the R gui in Windows, and rgedit in Linux (unfortunately doesn't work with current Ubuntu version). These have by default pop-out plot windows which you can fill the screen with. RStudio has a small plot panel so I didn't find that it worked so well there. If that still isn't big enough then I guess you would have to chop up your raster into smaller parts. I've found the gdalUtils package best for this sort of thing, and then you could probably use the same values from click_sample to classify all the parts of the map afterwards . However, I would have thought that limits regarding paper size of the historical map would mean that there shouldn't be so many situations where size of the map sheet and detail of the mapping would mean that you can't see where you are clicking. 

Sorry that I can't be of more help with this!
Alistair
