### ISSUE TITLE
Problem with class_map (Error in h(simpleError(msg, call)) :    ...)

### ISSUE THREAD

**Issue by colplainwil** [AGAuffret/HistMapR#3]
Hello, 

first of all I think this is a great package. I work with historical maps a lot and I think it would be great to digitize them automatically in some cases. 

To get started with the package, I wanted to try the example code proved on figshare (HistMapR_script.R). It works perfectly, until i use the function class_map. It always returns an error:

```
> test<-class_map(ras.smoothed.agg, colour.table=col.table, errors=2, exceptions="Forest", plot.raster = TRUE, raster.summary=FALSE, save.raster = FALSE)

 Raster categories:

	Arable = 1
	Open = 2
	Forest = 3

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': invalid layer names
```

It only plots the orig.raster and if I try to save the raster, the file is completely black. 

I am using R version 4.3.1 and ran the code exactly as it is in the HistMapR_script.R file.

Thank you for your trouble.

**Comment by AGAuffret** [comment]
Hi colplainwil,

I reproduced the error, made some changes and it is now working for me. So if you just reinstall the package it should work fine.

I noticed a related issue for writing the raster earlier this year, but had not corrected the part of the code for the plotting. Apologies, and thanks for getting in touch.

Alistair

**Comment by colplainwil** [comment]
Hi Alistair, 

I just tried it and it works now. Thank you very much!
